# Generated by Django 4.0.6 on 2022-07-11 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whisper', '0002_remove_session_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='session_id',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
