# Generated by Django 4.0.6 on 2022-07-15 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whisper', '0003_session_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='category',
            field=models.CharField(choices=[('buildings', 'Buildings'), ('movies', 'Movies'), ('music', 'Music'), ('travel', 'Travel'), ('food', 'Food'), ('water', 'Water'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AddField(
            model_name='room',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='whisper.user'),
        ),
        migrations.AlterField(
            model_name='room',
            name='users',
            field=models.ManyToManyField(related_name='users', to='whisper.user'),
        ),
    ]
