# Generated by Django 4.0.6 on 2022-07-15 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whisper', '0004_room_category_room_owner_alter_room_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='users',
        ),
    ]
